In [2]:
# Import all tools we need

# Regular EDA(exploratory data analysis) and plotting libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline  
# we want out plots to appear inside th notebook

# Models from Scikit-Learn
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

#Model Evaluation
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.model_selection import RandomizedSearchCV,GridSearchCV
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import RocCurveDisplay

In [3]:
#from google.colab import drive
#drive.mount('/content/drive')

In [4]:
## Load data
df = pd.read_csv("drive/MyDrive/Machine Learning/ASD/csv_result-1704.csv")
df

,id,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,used_app_before,result,age_desc,relation,Class/ASD,predictedclass,entropy,pro_dis: Iris-setosa,pro_dis: Iris-versicolor,pro_dis: Iris-virginica
0,1,1,1,0,0,1,1,0,1,0,...,no,5,4-11 years,Parent,NO,Iris-setosa,0.610864,0.700,0.300,0.000
1,2,1,1,0,0,1,1,0,1,0,...,no,5,4-11 years,Parent,NO,Iris-versicolor,0.000000,0.000,1.000,0.000
2,3,1,1,0,0,0,1,1,1,0,...,yes,5,4-11 years,?,NO,Iris-virginica,1.098513,0.333,0.333,0.333
3,4,0,1,0,0,1,1,0,0,0,...,no,4,4-11 years,?,NO,NaN,NaN,NaN,NaN,NaN
4,5,1,1,1,1,1,1,1,1,1,...,no,10,4-11 years,Parent,YES,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,288,1,1,1,1,1,1,1,1,1,...,no,10,4-11 years,Parent,YES,NaN,NaN,NaN,NaN,NaN
288,289,1,0,0,0,1,0,1,0,0,...,no,4,4-11 years,Parent,NO,NaN,NaN,NaN,NaN,NaN
289,290,1,0,1,1,1,1,1,0,0,...,no,7,4-11 years,Parent,YES,NaN,NaN,NaN,NaN,NaN
290,291,1,1,1,0,1,1,1,1,1,...,no,9,4-11 years,Parent,YES,NaN,NaN,NaN,NaN,NaN
291,292,0,0,1,0,1,0,1,0,0,...,no,3,4-11 years,Parent,NO,NaN,NaN,NaN,NaN,NaN

In [25]:
# Let's find out how many of each class there
df["Class/ASD"].value_counts()

NO     151
YES    141
Name: Class/ASD, dtype: int64

In [26]:
# Are there any missing values?
df.isna().sum()

id                            0
A1_Score                      0
A2_Score                      0
A3_Score                      0
A4_Score                      0
A5_Score                      0
A6_Score                      0
A7_Score                      0
A8_Score                      0
A9_Score                      0
A10_Score                     0
age                           0
gender                        0
ethnicity                     0
jundice                       0
austim                        0
result                        0
age_desc                      0
relation                      0
Class/ASD                     0
entropy                     289
pro_dis: Iris-setosa        289
pro_dis: Iris-versicolor    289
pro_dis: Iris-virginica     289
dtype: int64

In [28]:
df

,id,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,...,jundice,austim,result,age_desc,relation,Class/ASD,entropy,pro_dis: Iris-setosa,pro_dis: Iris-versicolor,pro_dis: Iris-virginica
0,1.0,1,1,0,0,1,1,0,1,0,...,no,no,5,4-11 years,Parent,NO,0.610864,0.700,0.300,0.000
1,2.0,1,1,0,0,1,1,0,1,0,...,no,no,5,4-11 years,Parent,NO,0.000000,0.000,1.000,0.000
2,3.0,1,1,0,0,0,1,1,1,0,...,no,no,5,4-11 years,?,NO,1.098513,0.333,0.333,0.333
3,4.0,0,1,0,0,1,1,0,0,0,...,yes,no,4,4-11 years,?,NO,NaN,NaN,NaN,NaN
4,5.0,1,1,1,1,1,1,1,1,1,...,yes,no,10,4-11 years,Parent,YES,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,288.0,1,1,1,1,1,1,1,1,1,...,yes,yes,10,4-11 years,Parent,YES,NaN,NaN,NaN,NaN
288,289.0,1,0,0,0,1,0,1,0,0,...,yes,yes,4,4-11 years,Parent,NO,NaN,NaN,NaN,NaN
289,290.0,1,0,1,1,1,1,1,0,0,...,no,no,7,4-11 years,Parent,YES,NaN,NaN,NaN,NaN
290,291.0,1,1,1,0,1,1,1,1,1,...,no,no,9,4-11 years,Parent,YES,NaN,NaN,NaN,NaN
291,292.0,0,0,1,0,1,0,1,0,0,...,no,no,3,4-11 years,Parent,NO,NaN,NaN,NaN,NaN

In [29]:
# Are there any missing values?
df.isna().sum()

id                            0
A1_Score                      0
A2_Score                      0
A3_Score                      0
A4_Score                      0
A5_Score                      0
A6_Score                      0
A7_Score                      0
A8_Score                      0
A9_Score                      0
A10_Score                     0
age                           0
gender                        0
ethnicity                     0
jundice                       0
austim                        0
result                        0
age_desc                      0
relation                      0
Class/ASD                     0
entropy                     289
pro_dis: Iris-setosa        289
pro_dis: Iris-versicolor    289
pro_dis: Iris-virginica     289
dtype: int64

In [36]:

df=df.drop(["entropy","pro_dis: Iris-virginica","result","age_desc","age"],axis='columns')
df=df.drop(["ethnicity"],axis='columns')

In [37]:
df

,id,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,gender,jundice,austim,Class/ASD
0,1.0,1,1,0,0,1,1,0,1,0,0,m,no,no,NO
1,2.0,1,1,0,0,1,1,0,1,0,0,m,no,no,NO
2,3.0,1,1,0,0,0,1,1,1,0,0,m,no,no,NO
3,4.0,0,1,0,0,1,1,0,0,0,1,f,yes,no,NO
4,5.0,1,1,1,1,1,1,1,1,1,1,m,yes,no,YES
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,288.0,1,1,1,1,1,1,1,1,1,1,f,yes,yes,YES
288,289.0,1,0,0,0,1,0,1,0,0,1,f,yes,yes,NO
289,290.0,1,0,1,1,1,1,1,0,0,1,m,no,no,YES
290,291.0,1,1,1,0,1,1,1,1,1,1,m,no,no,YES
291,292.0,0,0,1,0,1,0,1,0,0,0,f,no,no,NO

In [40]:
df['gender'] = df['gender'].replace({'m': 1, 'f': 0})
df['Class/ASD'] = df['Class/ASD'].replace({'YES': 1, 'NO': 0})
df['jundice'] = df['jundice'].replace({'yes': 1, 'no': 0})
df['austim'] = df['austim'].replace({'yes': 1, 'no': 0})

In [41]:
df

,id,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,gender,jundice,austim,Class/ASD
0,1.0,1,1,0,0,1,1,0,1,0,0,1,0,0,0
1,2.0,1,1,0,0,1,1,0,1,0,0,1,0,0,0
2,3.0,1,1,0,0,0,1,1,1,0,0,1,0,0,0
3,4.0,0,1,0,0,1,1,0,0,0,1,0,1,0,0
4,5.0,1,1,1,1,1,1,1,1,1,1,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,288.0,1,1,1,1,1,1,1,1,1,1,0,1,1,1
288,289.0,1,0,0,0,1,0,1,0,0,1,0,1,1,0
289,290.0,1,0,1,1,1,1,1,0,0,1,1,0,0,1
290,291.0,1,1,1,0,1,1,1,1,1,1,1,0,0,1
291,292.0,0,0,1,0,1,0,1,0,0,0,0,0,0,0

In [42]:
# Split data into x and y
x = df.drop("Class/ASD",axis=1)

y = df["Class/ASD"]
# Split data into train and test sets
# Split data into train and test sets
np.random.seed(42)

# Split into train and test
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [43]:
x.isna().sum()

id           0
A1_Score     0
A2_Score     0
A3_Score     0
A4_Score     0
A5_Score     0
A6_Score     0
A7_Score     0
A8_Score     0
A9_Score     0
A10_Score    0
gender       0
jundice      0
austim       0
dtype: int64

In [44]:
#df["id"] = [float(str(i).replace(",", "")) for i in df["id"]]
#df['object'] = df['object'].astype('int')
#df['age'] = df['age'].astype(int)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         292 non-null    float64
 1   A1_Score   292 non-null    int64
 2   A2_Score   292 non-null    int64
 3   A3_Score   292 non-null    int64
 4   A4_Score   292 non-null    int64
 5   A5_Score   292 non-null    int64
 6   A6_Score   292 non-null    int64
 7   A7_Score   292 non-null    int64
 8   A8_Score   292 non-null    int64
 9   A9_Score   292 non-null    int64
 10  A10_Score  292 non-null    int64
 11  gender     292 non-null    int64
 12  jundice    292 non-null    int64
 13  austim     292 non-null    int64
 14  Class/ASD  292 non-null    int64
dtypes: float64(1), int64(14)
memory usage: 34.3 KB

In [55]:
# Put models in a dictionary
models = {"Logistic Regression": LogisticRegression(),
         "KNN": KNeighborsClassifier(),
         "Random Forest": RandomForestClassifier()}

# Create a function to fit and score models
def fit_and_score(models,x_train,x_test,y_train,y_test):
    """
    Fits and evaluates given machine learning models.
    models : a dict of different Scikit-Learn ML models
    x_train : a training set(no labels)
    x_test : testing data(no labels)
    y_train : training labels
    y_test : test_labels
    """
    
    # Set random seed
    np.random.seed(42)
    # Make a dictionary to keep model scores
    model_scores = {}
    
    for name, model in models.items():
        # Fit the model to the data
        model.fit(x_train,y_train)
        # Evaluate the model and append its score to model_scores
        model_scores[name] = model.score(x_test,y_test)
        
    return model_scores

In [56]:
df.info()
x

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 292 entries, 0 to 291
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         292 non-null    float64
 1   A1_Score   292 non-null    int64
 2   A2_Score   292 non-null    int64
 3   A3_Score   292 non-null    int64
 4   A4_Score   292 non-null    int64
 5   A5_Score   292 non-null    int64
 6   A6_Score   292 non-null    int64
 7   A7_Score   292 non-null    int64
 8   A8_Score   292 non-null    int64
 9   A9_Score   292 non-null    int64
 10  A10_Score  292 non-null    int64
 11  gender     292 non-null    int64
 12  jundice    292 non-null    int64
 13  austim     292 non-null    int64
 14  Class/ASD  292 non-null    int64
dtypes: float64(1), int64(14)
memory usage: 34.3 KB

,id,A1_Score,A2_Score,A3_Score,A4_Score,A5_Score,A6_Score,A7_Score,A8_Score,A9_Score,A10_Score,gender,jundice,austim
0,1.0,1,1,0,0,1,1,0,1,0,0,1,0,0
1,2.0,1,1,0,0,1,1,0,1,0,0,1,0,0
2,3.0,1,1,0,0,0,1,1,1,0,0,1,0,0
3,4.0,0,1,0,0,1,1,0,0,0,1,0,1,0
4,5.0,1,1,1,1,1,1,1,1,1,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
287,288.0,1,1,1,1,1,1,1,1,1,1,0,1,1
288,289.0,1,0,0,0,1,0,1,0,0,1,0,1,1
289,290.0,1,0,1,1,1,1,1,0,0,1,1,0,0
290,291.0,1,1,1,0,1,1,1,1,1,1,1,0,0
291,292.0,0,0,1,0,1,0,1,0,0,0,0,0,0

In [57]:
model_scores = fit_and_score(models = models,
                            x_train=x_train,
                            x_test=x_test,
                            y_train = y_train,
                            y_test=y_test)
model_scores

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

{'Logistic Regression': 1.0,
 'KNN': 0.423728813559322,
 'Random Forest': 0.9661016949152542}

In [58]:
# Create a hyperparameter grid for RandomForestClassifier
rf_grid = {"n_estimators":np.arange(10,1000,50),
           "max_depth": [None,3,5,10],
           "min_samples_split":np.arange(2,20,2),
           "min_samples_leaf" : np.arange(1,20,2)
          }

In [59]:
np.random.seed(42)

#Setup random hyperparameter search for RandomForestClassifier
rs_rf = RandomizedSearchCV(RandomForestClassifier(),
                          param_distributions=rf_grid,
                          cv=5,
                          n_iter=20,
                          verbose=True)

#Fit random hyperparaeter search model for RandomForestClassifier()
rs_rf.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_iter=20,
                   param_distributions={'max_depth': [None, 3, 5, 10],
                                        'min_samples_leaf': array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]),
                                        'min_samples_split': array([ 2,  4,  6,  8, 10, 12, 14, 16, 18]),
                                        'n_estimators': array([ 10,  60, 110, 160, 210, 260, 310, 360, 410, 460, 510, 560, 610,
       660, 710, 760, 810, 860, 910, 960])},
                   verbose=True)

In [60]:
# Find the best hyperparameters
rs_rf.best_params_

{'n_estimators': 510,
 'min_samples_split': 14,
 'min_samples_leaf': 1,
 'max_depth': None}

In [61]:
# Evaluate the randomized searchCV for RandomForestClassifier model
rs_rf.score(x_test,y_test)

0.9830508474576272

In [65]:
import pickle
# create an iterator object with write permission - model.pkl
with open('drive/MyDrive/Machine Learning/ASD/as_model.pkl','wb') as files:
    pickle.dump(rs_rf, files)